name: Deploy to GitHub Pages
on:
  push:
    branches: [main]  # 监听 main 分支的推送
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install  # 如果是静态生成器，如 Vue/React
      - name: Build
        run: npm run build  # 生成静态文件到 dist/ 目录
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # 静态文件路径
